### ISSUE TITLE
Process to use non-standard organism index unclear

### ISSUE THREAD

**Issue by j-andrews7** [ialbert/genescape-central#12]
Following `genescape build`, it doesn't seem like providing the resulting index to `genescape web` does anything. "Human" and "Mouse" are still available in the dropdown, the index stats are the same on "Draw Tree" click - `utils.index_stats       index: 288,575 mappings,  19,606 symbols, 18,680 terms`, and plugging in symbols from the custom index results in no hits.

I may simply be doing something wrong, but a more clear example of how this can be done would be helpful.

**Comment by ialbert** [comment]
The documentation now notes how users need to invoke the tool to pass an index to it

     genescape tree --index myindex.gz genelist.txt
