### ISSUE TITLE
Light/dark green code coloring when filtering applied

### ISSUE THREAD

**Issue by j-andrews7** [ialbert/genescape-central#13]
Should the most granular leaf nodes color mapping be changed when filtering is applied? As an example, here's a few genes with all terms included:
![image](https://github.com/ialbert/genescape-central/assets/10225716/3c589953-3e95-44c6-90b9-692366555cd2)

All of the leaf nodes are light green, with the leaf nodes containing the most parent terms being dark green (please correct me if I'm interpreting this incorrectly).

If I limit to Biological Process terms, should the "adaptive immune response" node now be a dark green leaf node?

![image](https://github.com/ialbert/genescape-central/assets/10225716/a4786137-1973-4588-9d3c-ac9a3cabdf4c)

**Comment by ialbert** [comment]
this is a concept I should explain better in the docs and the paper, and I will give that a go

The leaf nodes are colored relative to the original annotation, the purpose is to indicate that annotation is at its maximal granularity (there are no additional nodes under this annotation).

A dark green means that the ontology has no terms that would be even more specific than that annotation.

A light green means there are more specific annotations, but none of the genes were annotated as such, 

So the green shade is an indicator of how good/specific the GO annotation were and would not change shade.

**Comment by j-andrews7** [comment]
Okay, I understand and agree that it could be explained a little more clearly. I think stating that the dark green nodes have no children terms would be helpful.

**Comment by ialbert** [comment]
Additional explanation added to the readme regarding the coloring.
