### ISSUE TITLE
More than one pattern term match

### ISSUE THREAD

**Issue by sridhar0605** [ialbert/genescape-central#17]
Its great that user can filter the resulting tree based certain key words. Can users use more than one keyword? I think currently this is not supported. 

Alternatively, if user provides a pattern on GUI or shiny, can the pattern label be added to png,pdf file as a prefix or suffix?

For example: 
Currently the default file that gets saved is `genescape.png` on the shiny app. 

If pattern `ligand` is supplied then the output plot should be `ligand_genescape.png`

**Comment by ialbert** [comment]
the pattern is interpreted as a regular expression, so it is easy to match multiple terms, 

      word1|word2|word3

but I should make that more clear and will do so in the docs

**Comment by sridhar0605** [comment]
Thanks a one line explanation in the docs would be great, I guess you can negate my output file prefix request I see how this can break things in user has more than one pattern.

**Comment by ialbert** [comment]
other issues with naming are that it is very common to filter by counts and by root (and I am exploring adding more filters in the future as we add more functionality). at that point it becomes onerous to embed all that information into the name.

In normal usecase the most common use is to keep filtering until I find something I want then save that and immediately rename it in a way that makes most sense to the project.

**Comment by ialbert** [comment]
Fixed in version 0.9.4., the main web interface has brief documentation at the bottom that describes the use of interface elements, noting that the pattern matching uses regular expressions.
