### ISSUE TITLE
Minor paper suggestions

### ISSUE THREAD

**Issue by j-andrews7** [ialbert/genescape-central#3]
The paper is pretty solid, just a few comments. Given the usage of networkx for the network generation, probably worth throwing a mention/reference to it into the text somewhere.

Other minor edits (recommended ~~deletions~~ or **additions**):

> For example, in the GO data, GO:0090630 defines _activation of GTPase activity_ and is a child of GO:0043547, which is ~~a~~ _positive regulation of GTPase activity_ which in turn is a child of GO:0051345 representing ~~a~~ _positive regulation of hydrolase activity_.

These two instances of "a" feel out of place.

> The complete human genome GAF representation contains 288,575 associations of 19,606 gene symbols **with** over 18,680 GO terms.

Seems like "with" is missing here.

>Since the resulting graphs may also be large, with thousands of nodes, the main interface provides input widgets that allow users to interactively reduce the subgraph to nodes for which:
> 1. The function definitions match certain patterns**.**
> 2. A minimum number of genes share a function**.**
> 3. Nodes belong to a specific GO subtree: Biological Process (BP), Molecular Function (MF), **or** Cellular Component (CC)**.**

Just unify punctuation of bullet points here.

**Comment by ialbert** [comment]
Word edits applied, added networkx as a citation.
