### ISSUE TITLE
Bug: duplicate inputs counted multiple times

### ISSUE THREAD

**Issue by j-andrews7** [ialbert/genescape-central#8]
What it says on the tin. Slapping the same gene in multiple times results in the final count for each term being misleading:

![image](https://github.com/ialbert/genescape-central/assets/10225716/f428ae5b-1b55-485a-89b8-45e7d7a12b02)

Uniquify the inputs on submission before anything else is done.

**Comment by ialbert** [comment]
This is a not a bug it is a feature :-) 

though it is debatable whether it is appropriate and whether imposing uniqueness is better

The tool also accepts GO terms as input,  so you could put in terms such as

GO:0016023 

One can even mix symbols and GO terms in the same input list.

some enrichment tools, like G:Profiler may produce GO: terms as output

in those cases the tool will add up the GO terms and produce the counts according to how many times a term was present, so it can be used to summarize GO terms, 

thus this behavior has utility and is not a mere oversight

**Comment by j-andrews7** [comment]
Hmm, perhaps a toggle then to enforce uniqueness? As a user, I don't think this is behavior I'd expect by default, so at least making it a little more clear in the documentation would be helpful.

**Comment by ialbert** [comment]
The behavior has utility so it has been kept as such, but a note is made in the docs about counting repeated elements.
