### ISSUE TITLE
Input box resizing can have some wonky behavior

### ISSUE THREAD

**Issue by j-andrews7** [ialbert/genescape-central#9]
This generally doesn't really impact use and is mostly a nitpick, but it'd be nice to bound the input box to the edge of the image so that it remains easily selectable.

![goof](https://github.com/ialbert/genescape-central/assets/10225716/3ef31767-f9a6-43a0-8334-d0d9d20e09ee)

**Comment by ialbert** [comment]
wonkiness hopefully fixed with Shiny interface
